---
title: "Clean MPI"
output:
  flexdashboard::flex_dashboard: null
runtime: shiny
resource_files:
- R/functions.R
---

```{r, include=FALSE}
library(tidyverse)
library(here)
library(patchwork)
source(here("R","functions.R"))
if (!dir.exists("raw_data")) dir.create("raw_data")
mpi_url_to_scrape <- "https://www2.gov.bc.ca/gov/content/employment-business/economic-development/industry/bc-major-projects-inventory/recent-reports"
mpi_scraped <- rvest::read_html(mpi_url_to_scrape)
dirty_links <- rvest::html_attr(rvest::html_nodes(mpi_scraped, "a"), "href")
mpi_links <- dirty_links[str_detect(dirty_links, ".xlsx")][2:23] #starts at 2 because we already have the latest
mpi_files <- paste0("mpi_dl", 1:length(mpi_links), ".xlsx") # sane file naming.
# NOTE THAT YOU ONLY NEED TO DOWNLOAD THE DATA ONCE PER QUARTER... FOLLOWING LINE CAN BE COMMENTED OUT TO SKIP DOWNLOAD
mapply(download.file, mpi_links, here::here("raw_data", mpi_files), mode="wb") # NOTE MODE="WB" FOR WINDOZ COMPATABILITY
########
mpi_all_sheets <- sapply(here::here("raw_data", mpi_files), readxl::excel_sheets) # gets all the sheets
sheet_starts_with_mpi <- lapply(mpi_all_sheets, function(x) x[startsWith(x, "mpi")]) %>%
  unlist(use.names = FALSE) # could break... assumes excel sheet naming remains consistent.
mpi_sheets <- c(sheet_starts_with_mpi) #only most recent files have same structure
mpi_files <- mpi_files[1:length(mpi_sheets)] # could break... assumes excel sheet naming remains consistent.
mpi_nested <- tibble(file = here::here("raw_data", mpi_files), sheet = mpi_sheets) %>%
  mutate(
    data = map2(file, sheet, readxl::read_excel),
    data = map(data, janitor::clean_names),
    data = map(data, fix_last_update), #replaces last update with modal value for the quarter.
    ncol = map_dbl(data, ncol)
  )

mpi_nested <- mpi_nested[!duplicated(mpi_nested$sheet),] #for some reason duplicates?
```

Inputs {.sidebar}
===============================================

N.B. expect a couple minute delay between uploading the file and the app becoming functional... there is a fair bit of processing to do.

```{r}
# inputs-------------------------

fileInput("file", 
          "Upload current raw MPI file:", 
          accept = c(".xlsx", ".xls"))


```

```{r}
renderUI({
  req(input$file)
  req(latest_data())
  req(all_data())
  req(mpi_raw())
  req(global_start_date())
  req(global_last_date())
  req(mode_filled())
  req(nested())
  req(mpi_clean())
  req(mpi_clean_current())
  req(mpi_raw_current())
  req(raw_and_clean_current())
  req(changed())
  req(changed_ids())
  selectInput(
      inputId = "project",
      label = "Select a project that was modified:",
      choices = changed_ids(),
      selected = changed_ids()[1])
})

```

#### Download the cleaned version of the current data:

```{r}
renderUI({
  req(input$file)  # Ensure a file is uploaded
  downloadHandler(
  filename = function() {
    "mpi_clean_current.csv"
  },
  content = function(file) {
    write.csv(mpi_clean_current(), file, row.names = FALSE) # Save tibble as a CSV file
  }
)
})
```

#### Download the cleaned version of all the data:


```{r}
renderUI({
  req(input$file)  # Ensure a file is uploaded
  downloadHandler(
  filename = function() {
    "mpi_clean.csv"
  },
  content = function(file) {
    write.csv(mpi_clean(), file, row.names = FALSE) # Save tibble as a CSV file
  }
)
})
```


```{r}
#reactive elements-----------------------------------
latest_data <- reactive({
  sheets <- readxl::excel_sheets(input$file$datapath)
  sheet <- sheets[str_detect(sheets,"mpi")]
  data <- readxl::read_excel(input$file$datapath, sheet=sheet)
  tibble(file=input$file$datapath, 
         sheet=sheet,
         data=list(data), 
         ncol=ncol(data))
})

all_data <- reactive({
  bind_rows(mpi_nested, latest_data())
})

mpi_raw <- reactive({
  data.table::rbindlist(all_data()$data, use.names = FALSE) %>%
  as_tibble() %>%
  mutate(
    last_update = lubridate::round_date(last_update, unit = "quarter") - months(1), 
    first_entry_date = lubridate::round_date(first_entry_date, unit = "quarter") - months(1),
    project_category_name = fct_collapse(project_category_name,
                                         `Residential & Commercial` = c(
                                           "Residential/Commercial",
                                           "Residential Commercial"
                                         )
    )
  )
})

 global_start_date <- reactive({min(mpi_raw()$last_update, na.rm = TRUE)}) # the date of the first MPI file used.
 global_last_date <- reactive({max(mpi_raw()$last_update, na.rm = TRUE)}) # the date of the last MPI file used.

mode_filled <- reactive({
  mpi_raw() %>%
  group_by(project_id) %>%
  nest() %>%
  mutate(data = map(data, mode_fill)) %>% # replace all the categorical variables that SHOULD be constant with their modal value
  unnest(data)
})

nested <- reactive({
  mode_filled()%>%
  group_by(project_id, #all the non variable variables
           project_name,
           project_description,
           construction_type,
           construction_subtype,
           project_type,
           region ,
           municipality,
           project_category_name,
           standardized_start_date,
           latitude,
           longitude,
           latitude_dms,
           longitude_dms
  ) %>%
  nest()%>%
  mutate(data = map(data, updown_fill))%>%
  arrange(project_id)
})

mpi_clean <- reactive({
  nested() %>%
  unnest(data)%>%
  select(project_id, #make sure the columns are in correct order
         project_name,
         project_description,
         estimated_cost,
         update_activity,
         environmental_assessment_stage,
         construction_type,
         construction_subtype,
         project_type,
         region,
         municipality,
         developer,
         architect,
         project_status,
         project_stage,
         project_category_name,
         public_funding_ind,
        # provinvial_funding,
         federal_funding,
         municipal_funding,
         other_public_funding,
         green_building_ind,
         green_building_desc,
         clean_energy_ind,
         indigenous_ind,
         indigenous_names,
         indigenous_agreement,
         construction_jobs,
         operating_jobs,
         standardized_start_date,
         standardized_completion_date,
         latitude,
         longitude,
         latitude_dms,
         longitude_dms,
         telephone,
         project_website,
         first_entry_date,
         last_update)%>%
  filter(last_update >= global_start_date()) # trim off data from before the date of the first file.
})

mpi_clean_current <- reactive({
  mpi_clean()%>%
  ungroup()%>%
  filter(last_update==max(last_update))
})

mpi_raw_current <- reactive({
  mpi_raw()%>%
  filter(last_update==max(last_update))%>%
  arrange(project_id)
})

raw_and_clean_current <- reactive({
  full_join(mpi_raw_current(), mpi_clean_current(), by="project_id", suffix = c("_raw","_clean"))%>% #add flags for changes
  mutate(project_name_change = if_else(project_name_clean == project_name_raw,
                                  FALSE,
                                  TRUE),
         project_description_change = if_else(project_description_clean==project_description_raw,
                                       FALSE,
                                       TRUE),
         estimated_cost_change = if_else(estimated_cost_clean == estimated_cost_raw,
                           FALSE,
                           TRUE),
         update_activity_change = if_else(update_activity_clean == update_activity_raw,
                           FALSE,
                           TRUE),
         environmental_assessment_stage_change = if_else(environmental_assessment_stage_clean == environmental_assessment_stage_raw,
                           FALSE,
                           TRUE),
         construction_type_change = if_else(construction_type_clean == construction_type_raw,
                           FALSE,
                           TRUE),
         construction_subtype_change = if_else(construction_subtype_clean == construction_subtype_raw,
                           FALSE,
                           TRUE),
         project_type_change = if_else(project_type_clean ==project_type_raw,
                           FALSE,
                           TRUE),
         region_change = if_else(region_clean == region_raw,
                           FALSE,
                           TRUE),
         municipality_change = if_else(municipality_clean == municipality_raw,
                           FALSE,
                           TRUE),
         developer_change = if_else(developer_clean == developer_raw,
                           FALSE,
                           TRUE),
         architect_change = if_else(architect_clean == architect_raw,
                           FALSE,
                           TRUE),
         project_status_change = if_else(project_status_clean == project_status_raw,
                           FALSE,
                           TRUE),
         project_stage_change = if_else(project_stage_clean == project_stage_raw,
                           FALSE,
                           TRUE),
         project_category_name_change = if_else(project_category_name_clean == project_category_name_raw,
                           FALSE,
                           TRUE),
         public_funding_ind_change = if_else(public_funding_ind_clean == public_funding_ind_raw,
                           FALSE,
                           TRUE),
         # provinvial_funding_change = if_else(provinvial_funding_clean == provinvial_funding_raw,
         #                   FALSE,
         #                   TRUE, TRUE),
         federal_funding_change = if_else(federal_funding_clean == federal_funding_raw,
                           FALSE,
                           TRUE),
         municipal_funding_change = if_else(municipal_funding_clean == municipal_funding_raw,
                           FALSE,
                           TRUE),
         other_public_funding_change = if_else(other_public_funding_clean == other_public_funding_raw,
                           FALSE,
                           TRUE),
         green_building_ind_change = if_else(green_building_ind_clean == green_building_ind_raw,
                           FALSE,
                           TRUE),
         green_building_desc_change = if_else(green_building_desc_clean == green_building_desc_raw,
                           FALSE,
                           TRUE),
         clean_energy_ind_change = if_else(clean_energy_ind_clean == clean_energy_ind_raw,
                           FALSE,
                           TRUE),
         indigenous_ind_change = if_else(indigenous_ind_clean == indigenous_ind_raw,
                           FALSE,
                           TRUE),
         indigenous_names_change = if_else(indigenous_names_clean == indigenous_names_raw,
                           FALSE,
                           TRUE),
         indigenous_agreement_change = if_else(indigenous_agreement_clean == indigenous_agreement_raw,
                           FALSE,
                           TRUE),
         construction_jobs_change = if_else(construction_jobs_clean == construction_jobs_raw,
                           FALSE,
                           TRUE),
         operating_jobs_change = if_else(operating_jobs_clean == operating_jobs_raw,
                           FALSE,
                           TRUE),
         standardized_start_date_change = if_else(standardized_start_date_clean == standardized_start_date_raw,
                           FALSE,
                           TRUE),
         standardized_completion_date_change = if_else(standardized_completion_date_clean == standardized_completion_date_raw,
                           FALSE,
                           TRUE),
         latitude_change = if_else(latitude_clean == latitude_raw,
                           FALSE,
                           TRUE),
         longitude_change = if_else(longitude_clean == longitude_raw,
                           FALSE,
                           TRUE),
         latitude_dms_change = if_else(latitude_dms_clean == latitude_dms_raw,
                           FALSE,
                           TRUE),
         longitude_dms_change = if_else(longitude_dms_clean == longitude_dms_raw,
                           FALSE,
                           TRUE),
         telephone_change = if_else(telephone_clean == telephone_raw,
                           FALSE,
                           TRUE),
         project_website_change = if_else(project_website_clean == project_website_raw,
                           FALSE,
                           TRUE),
         first_entry_date_change = if_else(first_entry_date_clean == first_entry_date_raw,
                           FALSE,
                           TRUE),
         last_update_change = if_else(last_update_clean ==last_update_raw,
                           FALSE,
                           TRUE)
  )
})

changed <- reactive({
  raw_and_clean_current()|>
  filter(estimated_cost_change==TRUE |
           construction_type_change==TRUE |
           construction_subtype_change==TRUE |
           region_change==TRUE |
           project_status_change==TRUE |
           project_stage_change==TRUE |
           project_category_name_change == TRUE)|>
  select(project_id,
         project_name_raw,
         contains("estimated_cost"),
         contains("construction_type"),
         contains("contstruction_subtype"),
         contains("region"),
         contains("project_status"),
         contains("project_stage"),
         contains("project_category_name")
         )|>
  arrange(desc(estimated_cost_raw))
})

changed_ids <- reactive({
  changed()|>
    pull(project_id)
})

raw <- reactive({
  mpi_raw()|>
    filter(project_id==input$project)
})
clean <- reactive({
  mpi_clean()|>
    filter(project_id==input$project)
})

```


Plots 
================================================

Row 
-------------------------------------

###

```{r}
renderPlot({
req(input$project)
plt1 <- compare(raw(),clean(), estimated_cost, "estimated_cost") 
plt2 <- compare(raw(),clean(), construction_type, "construction_type")
plt3 <- compare(raw(),clean(), construction_subtype, "construction_subtype")
plt4 <- compare(raw(),clean(), project_status, "project_status")
plt5 <- compare(raw(),clean(), project_stage, "project_stage")
plt6 <- compare(raw(),clean(), project_category_name, "project_category_name")
 
(plt1+plt2+plt3)/(plt4+plt5+plt6)

})
```

Table
================================================

### 

```{r}
DT::renderDT({
  req(input$file)  # Ensure a file is uploaded
  DT::datatable(changed(), rownames=FALSE, filter="top")
})
```


