---
title: 'Major Project Inventory: data quality'
date: "`r paste0('updated: ',as.Date(file.info(here::here('processed_data','plots.rds'))$mtime-lubridate::hours(7)))`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: https://github.com/bcgov/mpi_data_quality
    css: style.css
runtime: shiny
resource_files:
- processed_data/plots.rds
- processed_data/plots_long.rds
- processed_data/mpi_fabricated_vs_raw.rds
- processed_data/mpi_clean_vs_raw.rds
- processed_data/mpi_fabricated_long.rds
- processed_data/mpi_clean_long.rds
- processed_data/mpi_raw_long.rds
---

```{r global, include=FALSE}
# Copyright 2022 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# libraries----------
if (!"tidyverse" %in% names(sessionInfo()$otherPkgs)) library(tidyverse)
if (!"lubridate" %in% names(sessionInfo()$otherPkgs)) library(lubridate) # years and months not exported objects
plots <- readRDS(here::here("processed_data", "plots.rds")) %>%
  mutate(facet_by = str_to_title(str_replace_all(facet_by, "_", " ")))
plots_long <- readRDS(here::here("processed_data", "plots_long.rds")) %>%
  mutate(facet_by = str_to_title(str_replace_all(facet_by, "_", " ")))
mpi_raw_long <- readRDS(here::here("processed_data", "mpi_raw_long.rds")) %>%
  mutate(data_type = "raw")
mpi_clean_long <- readRDS(here::here("processed_data", "mpi_clean_long.rds")) %>%
  mutate(data_type = "clean") %>%
  select(-weight)
mpi_fabricated_long <- readRDS(here::here("processed_data", "mpi_fabricated_long.rds")) %>%
  mutate(data_type = "fabricated") %>%
  select(-weight)
clean_vs_raw <- readRDS(here::here("processed_data", "mpi_clean_vs_raw.rds"))
fabricated_vs_raw  <- readRDS(here::here("processed_data", "mpi_fabricated_vs_raw.rds"))
#functions---------
downloadButtonRmd <- function (outputId, label = "Download", class = NULL, ...)  {
     tags$a(id = outputId, class = paste("btn btn-default shiny-download-link", 
        class), href = "", target = "_blank", download = NA, 
        icon("download"), label, ...)
 }
```

Web data
=====================================     

Inputs {.sidebar data-width=400}
-------------------------------------

```{r}
selectInput(
  "facet_var",
  "What variable do you want to facet by?",
  plots$facet_by,
  selected = plots$facet_by[1],
  multiple = FALSE
)
```

* Raw data is sourced from [Economic Development](https://www2.gov.bc.ca/gov/content/employment-business/economic-development/industry/bc-major-projects-inventory/recent-reports) with no processing.

* Clean data corrects for two main problems in the data:
  + Mis-categorization: some projects change categories mid-project. 
  + Missing values, both explicit (the presence of an absence i.e. value recorded as NA) and implicit (the absence of a presence i.e. project missing from MPI).

* In order to clean the data:
  + For each project the reported categories are replaced with that project's modal (most common) reported category.
  + Implicit missing values are converted to explicit missing values by left joining 1) a regular grid of quarterly dates with 2) the observed data.
  + Finally the explicit missing variables (estimated_cost, telephone, project_status, first_entry_date) are "updown" filled:  First missing values are filled up (backwards in time) and then down (forwards in time).

*  Fabricated data replaces remaining NA values (projects that have never reported an estimated cost) with a guess of the estimated cost.
*  The guess is the mean of: 
    + The average estimated cost for all projects of the same construction_type, construction_subtype, project_type and project_category_name.
    + 15M, which is the minimum project size to be considered "Major".

Column
-----------------------------------------------------------------------

###

```{r}
plotly::renderPlotly({
  plt <- plots %>%
    filter(facet_by == input$facet_var) %>%
    select(plot) %>%
    pull()
  plt[[1]]
}) %>%
  bindCache(input$facet_var)
```

Long data: 
=====================================     

Inputs {.sidebar data-width=400}
-------------------------------------

```{r}
selectInput(
  "facet_var_long",
  "What variable do you want to facet by?",
  plots_long$facet_by,
  selected = plots_long$facet_by[1],
  multiple = FALSE
)
```

* Raw data is sourced from file "MPIlongraw.xlsx".

* Clean data corrects for two main problems in the data:
  + Mis-categorization: some projects change categories mid-project. 
  + Missing values, both explicit (the presence of an absence i.e. value recorded as NA) and implicit (the absence of a presence i.e. project missing from MPI).

* In order to clean the data:
  + For each project the reported categories are replaced with that project's modal (most common) reported category.
  + Implicit missing values are converted to explicit missing values by joining to a regular grid of quarterly dates.
  + Finally the explicit missing variables (estimated_cost, project_status) are "updown" filled:  First missing values are filled backwards in time and then forwards in time.

*  Fabricated data replaces remaining NA values (projects that have never reported an estimated cost) with the mean of: 
    + The average estimated cost for all projects of the same project_type and region.
    + 15M, which is the minimum project size to be considered "Major".

### Download Data:
    
```{r}
output$clean <- downloadHandler(filename = function() { 
   "clean_MPI.csv"
 },
 content = function(file) {
   write_csv(mpi_clean_long, file)
 })
output$fabricated <- downloadHandler(filename = function() { 
   "fabricated_MPI.csv"
 },
 content = function(file) {
   write_csv(mpi_fabricated_long, file)
 })

output$clean_vs_raw <- downloadHandler(filename = function() { 
   "clean_vs_raw_MPI.csv"
 },
 content = function(file) {
   write_csv(clean_vs_raw, file)
 })
output$fabricated_vs_raw <- downloadHandler(filename = function() { 
   "fabricated_vs_raw_MPI.csv"
 },
 content = function(file) {
   write_csv(fabricated_vs_raw, file)
 })
```

```{r}
downloadButtonRmd("clean", label = "Download clean data")
```

<br>

```{r}
downloadButtonRmd("fabricated", label = "Download fabricated data")
```
  
<br>    

```{r}
downloadButtonRmd("clean_vs_raw", label = "Download clean vs. raw data")
```
  
<br>    

```{r}
downloadButtonRmd("fabricated_vs_raw", label = "Download fabricated vs. raw data")
```
  
<br>    


Column 
-----------------------------------------------------------------------

### Plots:

```{r}
plotly::renderPlotly({
  plt <- plots_long %>%
    filter(facet_by == input$facet_var_long) %>%
    select(plot) %>%
    pull()
  plt[[1]]
}) %>%
  bindCache(input$facet_var_long)
```






